version: "3.8"

services:
  api:
    container_name: fastapi-api_container
    build:
      context: ./project
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3.10-bullseye
    image: api:fastapi
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      # Host:Container
      - 9000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@api-db:5432/api_test
    networks:
      - api_gateway
    depends_on:
      - api-db

  api-db:
    container_name: fastapi-db_container
    build:
      context: ./project/db
      dockerfile: Dockerfile
      args:
        VARIANT: 14-alpine
    image: postgres-db:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - api_gateway
      - db_gateway

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - db_gateway

volumes:
  postgres-data:

networks:
  api_gateway:
  db_gateway:
